class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'SHEild AI',
      'home': 'Home',
      'routes': 'Route',
      'sos': 'SOS',
      'alerts': 'Alert',
      'profile': 'Profile',
      'shield_ai': 'SHEild AI',
      // SignIn
      'your_companion': 'Your Companion for a Safer Tomorrow',
      'create_profile': 'Create Your Profile',
      'enter_details': 'Enter your details to activate protection',
      'full_name': 'Full Name',
      'enter_name': 'Enter your name',
      'mobile_number': 'Mobile Number',
      'ten_digit': '10-digit number',
      'trusted_contacts': 'Trusted Contacts (Sentinels)',
      'contact_n': 'Contact',
      'ten_digits': '(10-digits)',
      'activate_protection': 'Activate Protection',
      'setting_up': 'Setting Up...',
      'location_info': 'Location access is required for emergency alerts. Your data is never shared.',
      'missing_fields': 'Missing Fields',
      'missing_fields_msg': 'Please fill in your name, phone and at least one emergency contact.',
      'invalid_phone': 'Invalid Phone',
      'invalid_phone_msg': 'Please enter a valid 10-digit mobile number.',
      'error': 'Error',
      'error_msg': 'Something went wrong. Please try again.',
      // Permissions Screen
      'your_security_setup': 'Your Security Setup',
      'security_setup_desc': 'This app can only protect you if permissions are granted. We will guide you through 4 quick steps to ensure maximum safety.',
      'always_on_location': 'Always-On Location',
      'location_desc': 'Allows your emergency contacts to track your exact position instantly when SOS is activated.',
      'location_fallback': 'Without location permission, contacts won\'t know where you are during an emergency.',
      'camera_microphone': 'Camera & Microphone',
      'av_desc': 'Enables autonomous capture of background evidence to legally document incidents without your interaction.',
      'av_fallback': 'Without camera or microphone access, audio and video evidence won\'t be recorded during your SOS.',
      'immediate_alerts': 'Immediate Alerts',
      'notif_desc': 'Keeps our monitoring engine running in the background to proactively warn you when you enter high-risk zones.',
      'notif_fallback': 'Without notifications, you won\'t receive immediate warnings about nearby dangers.',
      'emergency_sms': 'Emergency SMS',
      'sms_desc': 'Automatically dispatches SOS text messages with a Google Maps link to your trusted contacts, even offline.',
      'sms_fallback': 'Without SMS access, automatic emergency texts cannot be sent to your guardians.',
      'start_setup': 'Start Setup',
      'grant_continue': 'Grant & Continue',
      'grant_finish': 'Grant & Finish',
      'skip': 'Skip (App will not be fully active)',
      'step': 'Step',
      'of': 'of',
      'protected': '% protected',
      'almost_protected': 'You\'re almost fully protected!',
      // Home Screen
      'scanning': 'Scanning safe corridors...',
      'safe_zone_label': 'SAFE ZONE',
      'danger_level': 'DANGER LEVEL',
      'risk_label': 'Risk',
      'i_am_safe_title': 'I\'M SAFE',
      'where_heading': 'Where are you heading?',
      'safe_route': 'Safe Route',
      'night_multiplier_active': '🌙 Night Multiplier ×{{value}} active',
      'safety_alert_feed': 'SAFETY ALERT FEED',
      'action_required': 'Action Required',
      // SOS Screen
      'sos_active': '🔴 SOS SESSION ACTIVE',
      'sos_idle': '✅ PROTECTION READY',
      'active_session': 'ACTIVE SESSION',
      'started': 'STARTED',
      'duration': 'DURATION',
      'location': 'LOCATION',
      'acquiring': 'Acquiring...',
      'rec': 'REC',
      'capturing_evidence': 'Capturing Evidence',
      'auto_stop_in': 'AUTO-STOP IN',
      'stop_recording': 'Stop Recording',
      'sos_active_init': 'SOS Initialized — Sending alerts & starting recording...',
      'stop_sos_button': 'Stop SOS Immediately',
      'rec_done_text': 'Evidence captured. Your SOS session is still active. Press "I\'m Safe" when you are secure.',
      'i_am_safe_sub': 'Cancel session & notify guardians',
      'i_am_safe_hint': 'Tapping this will end your SOS and send a confirmation to your sentinels.',
      'trigger_sos': 'TRIGGER SOS',
      'trigger_sos_sub': 'Tap to send emergency alerts instantly',
      'trigger_sos_meta1': 'Auto-records evidence',
      'trigger_sos_meta2': 'SMS + Live Tracking',
      'no_active_session': 'No active session. Tap',
      'trigger_sos_cta': '\'TRIGGER SOS\'',
      'no_active_session2': 'to alert your guardians and start recording.',
      // Alerts Screen
      'report_observation': 'Report Observation',
      'help_others_msg': 'See something suspicious? Help protect the community by sharing anonymously.',
      'report_now': 'Report Now',
      'system_vigilant': 'System Vigilant',
      'no_alerts': 'No active alerts in your area. Stay aware.',
      // Profile Screen
      'profile_title': 'My Profile',
      'status_label': 'Status',
      'risk_level_stat': 'RISK LEVEL',
      'active': 'Active',
      'security_model': 'SECURITY MODEL',
      'account_settings': 'ACCOUNT SETTINGS',
      'personal_information': 'Personal Information',
      'sos_guardians': 'SOS Guardians',
      'contacts_active': 'contacts active',
      'app_preferences': 'APP PREFERENCES',
      'safety_notifications': 'Safety Notifications',
      'app_language': 'App Language',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'return_home': 'Return to Home',
      // Personal Info
      'personal_info': 'Personal Information',
      'save': 'Save',
      'edit': 'Edit',
      'full_name_label': 'FULL NAME',
      'mobile_label': 'MOBILE NUMBER',
      // SOS Contacts
      'sentinel_contacts': 'Sentinel Contacts',
      'cancel': 'Cancel',
      'emergency_guardians': 'Emergency Guardians',
      'guardians_desc': 'These contacts receive your live location and SOS alert immediately. Choose people you trust unconditionally.',
      'no_contacts': 'No emergency contacts set up.',
      'set_up': 'SET UP',
      'manage_contacts': 'Manage Contacts',
      'trusted_contacts_max': 'Trusted Contacts (max 5)',
      'verify_save': '✔ Verify & Save',
      'safety_protocol': 'Safety Protocol',
      'tip1': 'Contacts receive real-time SMS with your live Google Maps link.',
      'tip2': 'All data is encrypted end-to-end. Privacy guaranteed.',
      // Language Screen
      'language': 'App Language',
      'select_preference': 'SELECT YOUR PREFERENCE',
      // Notifications Settings
      'notification_prefs': 'Notification Preferences',
      'alert_types': 'ALERT TYPES',
      'zone_entry_alerts': 'Zone Entry Alerts',
      'zone_entry_desc': 'Get warned when entering high-risk areas.',
      'community_alerts': 'Community Alerts',
      'community_alerts_desc': 'Receive reports from nearby Sentinel users.',
      'sos_confirmation': 'SOS Confirmation',
      'sos_conf_desc': 'Get a push when your guardians acknowledge your SOS.',
      'safety_check_in': 'Safety Check-In',
      'safety_check_desc': 'Periodic check to confirm you are safe.',
      // Safety Check Modal
      'safety_check': 'Safety Check',
      'safety_check_msg': 'Are you safe? Please confirm or trigger SOS if you need help.',
      'i_am_safe': 'I Am Safe',
      'send_sos': 'SEND SOS',
    },
    'hi': {
      'app_name': 'SHEild AI',
      'home': 'होम',
      'routes': 'रूट',
      'sos': 'SOS',
      'alerts': 'अलर्ट',
      'profile': 'प्रोफ़ाइल',
      'shield_ai': 'SHEild AI',
      'your_companion': 'एक सुरक्षित कल के लिए आपका साथी',
      'create_profile': 'अपनी प्रोफ़ाइल बनाएं',
      'enter_details': 'सुरक्षा सक्रिय करने के लिए विवरण दर्ज करें',
      'full_name': 'पूरा नाम',
      'enter_name': 'अपना नाम दर्ज करें',
      'mobile_number': 'मोबाइल नंबर',
      'ten_digit': '10-अंकीय नंबर',
      'trusted_contacts': 'विश्वसनीय संपर्क (सेंटिनल)',
      'contact_n': 'संपर्क',
      'ten_digits': '(10-अंक)',
      'activate_protection': 'सुरक्षा सक्रिय करें',
      'setting_up': 'सेटअप हो रहा है...',
      'location_info': 'आपातकालीन अलर्ट के लिए स्थान की आवश्यकता है।',
      'missing_fields': 'अधूरी जानकारी',
      'missing_fields_msg': 'कृपया अपना नाम, फ़ोन और कम से कम एक संपर्क भरें।',
      'invalid_phone': 'अमान्य फ़ोन',
      'invalid_phone_msg': 'कृपया 10-अंकीय मोबाइल नंबर दर्ज करें।',
      'error': 'त्रुटि',
      'error_msg': 'कुछ गलत हो गया। पुनः प्रयास करें।',
      'where_heading': 'आप कहाँ जा रहे हैं?',
      'safe_route': 'सुरक्षित रूट',
      'trigger_sos': 'SOS ट्रिगर करें',
      'trigger_sos_sub': 'तुरंत आपातकालीन अलर्ट भेजने के लिए टैप करें',
      'trigger_sos_meta1': 'स्वचालित साक्ष्य रिकॉर्ड',
      'trigger_sos_meta2': 'SMS + लाइव ट्रैकिंग',
      'i_am_safe_title': 'मैं सुरक्षित हूँ',
      'i_am_safe': 'मैं सुरक्षित हूँ',
      'send_sos': 'SOS भेजें',
      'profile_title': 'मेरी प्रोफ़ाइल',
      'personal_information': 'व्यक्तिगत जानकारी',
      'sos_guardians': 'SOS संरक्षक',
      'contacts_active': 'संपर्क सक्रिय',
      'app_preferences': 'ऐप प्राथमिकताएं',
      'safety_notifications': 'सुरक्षा अधिसूचनाएं',
      'app_language': 'ऐप भाषा',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'return_home': 'होम पर वापस जाएं',
      'personal_info': 'व्यक्तिगत जानकारी',
      'save': 'सहेजें',
      'edit': 'संपादित करें',
      'language': 'ऐप भाषा',
      'select_preference': 'अपनी पसंद चुनें',
      'account_settings': 'खाता सेटिंग',
      'status_label': 'स्थिति',
      'risk_label': 'जोखिम',
      'active': 'सक्रिय',
      'security_model': 'सुरक्षा मॉडल',
      'risk_level_stat': 'जोखिम स्तर',
      'sentinel_contacts': 'सेंटिनल संपर्क',
      'cancel': 'रद्द करें',
      'report_observation': 'अवलोकन रिपोर्ट करें',
      'report_now': 'अभी रिपोर्ट करें',
      'safety_alert_feed': 'सुरक्षा अलर्ट फ़ीड',
      'system_vigilant': 'सिस्टम सतर्क',
      'no_alerts': 'आपके क्षेत्र में कोई सक्रिय अलर्ट नहीं।',
      'safety_check': 'सुरक्षा जांच',
      'safety_check_msg': 'क्या आप सुरक्षित हैं?',
      'sos_active': '🔴 SOS सत्र सक्रिय',
      'sos_idle': '✅ सुरक्षा तैयार',
      'no_active_session': 'कोई सक्रिय सत्र नहीं।',
      'trigger_sos_cta': '\'SOS ट्रिगर करें\'',
      'no_active_session2': 'अपने संरक्षकों को सचेत करने के लिए टैप करें।',
      'emergency_guardians': 'आपातकालीन संरक्षक',
      'guardians_desc': 'ये संपर्क तुरंत आपका स्थान प्राप्त करते हैं।',
      'no_contacts': 'कोई आपातकालीन संपर्क नहीं।',
      'set_up': 'सेट अप करें',
      'manage_contacts': 'संपर्क प्रबंधित करें',
      'trusted_contacts_max': 'विश्वसनीय संपर्क (अधिकतम 5)',
      'verify_save': '✔ सत्यापित करें और सहेजें',
    },
    'mr': {
      'app_name': 'SHEild AI',
      'home': 'होम',
      'routes': 'मार्ग',
      'sos': 'SOS',
      'alerts': 'सूचना',
      'profile': 'प्रोफाइल',
      'shield_ai': 'SHEild AI',
      'your_companion': 'एक सुरक्षित उद्यासाठी तुमचा साथी',
      'create_profile': 'तुमची प्रोफाइल तयार करा',
      'activate_protection': 'संरक्षण सक्रिय करा',
      'trigger_sos': 'SOS सुरू करा',
      'i_am_safe_title': 'मी सुरक्षित आहे',
      'i_am_safe': 'मी सुरक्षित आहे',
      'where_heading': 'तुम्ही कुठे जात आहात?',
      'safe_route': 'सुरक्षित मार्ग',
      'profile_title': 'माझी प्रोफाइल',
      'save': 'जतन करा',
      'edit': 'संपादित करा',
      'cancel': 'रद्द करा',
      'app_language': 'अ‍ॅप भाषा',
      'language': 'अ‍ॅप भाषा',
      'select_preference': 'तुमची प्राधान्य निवडा',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'return_home': 'होमवर परत जा',
    },
    'gu': {
      'app_name': 'SHEild AI',
      'home': 'હોમ',
      'routes': 'રૂટ',
      'sos': 'SOS',
      'alerts': 'ચેતવણી',
      'profile': 'પ્રોફાઇલ',
      'shield_ai': 'SHEild AI',
      'your_companion': 'સુરક્ષિત કાલ માટે તમારો સાથી',
      'create_profile': 'તમારી પ્રોફાઇલ બનાવો',
      'activate_protection': 'રક્ષણ સક્રિય કરો',
      'trigger_sos': 'SOS ટ્રિગર કરો',
      'i_am_safe_title': 'હું સુરક્ષિત છું',
      'i_am_safe': 'હું સુરક્ષિત છું',
      'where_heading': 'તમે ક્યાં જઈ રહ્યા છો?',
      'safe_route': 'સુરક્ષિત રૂટ',
      'profile_title': 'મારી પ્રોફાઇલ',
      'save': 'સાચવો',
      'edit': 'સંપાદિત કરો',
      'cancel': 'રદ કરો',
      'app_language': 'એપ ભાષા',
      'language': 'એપ ભાષા',
      'select_preference': 'તમારી પ્રાધાન્યતા પસંદ કરો',
      'dark_mode': 'ડાર્ક મોડ',
      'light_mode': 'લાઇટ મોડ',
      'return_home': 'હોમ પર પાછા જાઓ',
    },
    'ta': {
      'app_name': 'SHEild AI',
      'home': 'முகப்பு',
      'routes': 'வழி',
      'sos': 'SOS',
      'alerts': 'எச்சரிக்கை',
      'profile': 'சுயவிவரம்',
      'shield_ai': 'SHEild AI',
      'your_companion': 'பாதுகாப்பான நாளைக்கு உங்கள் தோழர்',
      'create_profile': 'உங்கள் சுயவிவரத்தை உருவாக்கவும்',
      'activate_protection': 'பாதுகாப்பை செயல்படுத்தவும்',
      'trigger_sos': 'SOS தொடங்கவும்',
      'i_am_safe_title': 'நான் பாதுகாப்பாக இருக்கிறேன்',
      'i_am_safe': 'நான் பாதுகாப்பாக இருக்கிறேன்',
      'where_heading': 'நீங்கள் எங்கே போகிறீர்கள்?',
      'safe_route': 'பாதுகாப்பான வழி',
      'profile_title': 'என் சுயவிவரம்',
      'save': 'சேமி',
      'edit': 'திருத்து',
      'cancel': 'ரத்து செய்',
      'app_language': 'செயலி மொழி',
      'language': 'செயலி மொழி',
      'select_preference': 'உங்கள் விருப்பத்தை தேர்ந்தெடுக்கவும்',
      'dark_mode': 'இருள் பயன்முறை',
      'light_mode': 'ஒளி பயன்முறை',
      'return_home': 'முகப்புக்கு திரும்பு',
    },
    'te': {
      'app_name': 'SHEild AI',
      'home': 'హోమ్',
      'routes': 'మార్గం',
      'sos': 'SOS',
      'alerts': 'హెచ్చరిక',
      'profile': 'ప్రొఫైల్',
      'shield_ai': 'SHEild AI',
      'your_companion': 'సురక్షితమైన రేపు కోసం మీ సాహచర్యం',
      'create_profile': 'మీ ప్రొఫైల్ సృష్టించండి',
      'activate_protection': 'రక్షణ సక్రియం చేయండి',
      'trigger_sos': 'SOS ప్రారంభించండి',
      'i_am_safe_title': 'నేను సురక్షితంగా ఉన్నాను',
      'i_am_safe': 'నేను సురక్షితంగా ఉన్నాను',
      'where_heading': 'మీరు ఎక్కడికి వెళ్తున్నారు?',
      'safe_route': 'సురక్షిత మార్గం',
      'profile_title': 'నా ప్రొఫైల్',
      'save': 'సేవ్',
      'edit': 'సవరించు',
      'cancel': 'రద్దు',
      'app_language': 'యాప్ భాష',
      'language': 'యాప్ భాష',
      'select_preference': 'మీ ప్రాధాన్యత ఎంచుకోండి',
      'dark_mode': 'డార్క్ మోడ్',
      'light_mode': 'లైట్ మోడ్',
      'return_home': 'హోమ్‌కి తిరిగి వెళ్ళండి',
    },
    'pa': {
      'app_name': 'SHEild AI',
      'home': 'ਘਰ',
      'routes': 'ਰੂਟ',
      'sos': 'SOS',
      'alerts': 'ਅਲਰਟ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'shield_ai': 'SHEild AI',
      'your_companion': 'ਸੁਰੱਖਿਅਤ ਕੱਲ੍ਹ ਲਈ ਤੁਹਾਡਾ ਸਾਥੀ',
      'create_profile': 'ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ',
      'activate_protection': 'ਸੁਰੱਖਿਆ ਸਕਿਰਿਅ ਕਰੋ',
      'trigger_sos': 'SOS ਸ਼ੁਰੂ ਕਰੋ',
      'i_am_safe_title': 'ਮੈਂ ਸੁਰੱਖਿਅਤ ਹਾਂ',
      'i_am_safe': 'ਮੈਂ ਸੁਰੱਖਿਅਤ ਹਾਂ',
      'where_heading': 'ਤੁਸੀਂ ਕਿੱਥੇ ਜਾ ਰਹੇ ਹੋ?',
      'safe_route': 'ਸੁਰੱਖਿਅਤ ਰੂਟ',
      'profile_title': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
      'save': 'ਸੇਵ ਕਰੋ',
      'edit': 'ਸੰਪਾਦਿਤ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'app_language': 'ਐਪ ਭਾਸ਼ਾ',
      'language': 'ਐਪ ਭਾਸ਼ਾ',
      'select_preference': 'ਆਪਣੀ ਪਸੰਦ ਚੁਣੋ',
      'dark_mode': 'ਡਾਰਕ ਮੋਡ',
      'light_mode': 'ਲਾਈਟ ਮੋਡ',
      'return_home': 'ਘਰ ਵਾਪਸ ਜਾਓ',
    },
    'bn': {
      'app_name': 'SHEild AI',
      'home': 'হোম',
      'routes': 'রুট',
      'sos': 'SOS',
      'alerts': 'সতর্কতা',
      'profile': 'প্রোফাইল',
      'shield_ai': 'SHEild AI',
      'your_companion': 'একটি নিরাপদ আগামীর জন্য আপনার সঙ্গী',
      'create_profile': 'আপনার প্রোফাইল তৈরি করুন',
      'activate_protection': 'সুরক্ষা সক্রিয় করুন',
      'trigger_sos': 'SOS শুরু করুন',
      'i_am_safe_title': 'আমি নিরাপদ',
      'i_am_safe': 'আমি নিরাপদ',
      'where_heading': 'আপনি কোথায় যাচ্ছেন?',
      'safe_route': 'নিরাপদ রুট',
      'profile_title': 'আমার প্রোফাইল',
      'save': 'সংরক্ষণ',
      'edit': 'সম্পাদনা',
      'cancel': 'বাতিল',
      'app_language': 'অ্যাপ ভাষা',
      'language': 'অ্যাপ ভাষা',
      'select_preference': 'আপনার পছন্দ নির্বাচন করুন',
      'dark_mode': 'ডার্ক মোড',
      'light_mode': 'লাইট মোড',
      'return_home': 'হোমে ফিরুন',
    },
  };

  static String get(String key, String lang) {
    return translations[lang]?[key] ?? translations['en']?[key] ?? key;
  }
}
